### ISSUE TITLE
Option to customize resolved dependencies download directory

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/VersionedBinaryArtifacts#14]
This is a request on behalf of @nikhilpathania and @jonasvinther 

Currently, the dependencies are always downloaded to `build/resolvedDep`. We would like an option to specify another location.

If I search for `resolvedDep` in the project, I find two possible code changes:
https://github.com/Praqma/VersionedBinaryArtifacts/search?utf8=%E2%9C%93&q=resolveddep&type=

- One in `BuildPublishing.groovy`
- One in `BuildExtension.groovy`

We are happy to work on the change ourselves, if @naesheim or @meekrosoft can get us started:
- Can you sketch what the change would look like? Can we just read a variable in the code and set it as a Gradle property in a project? Do we need to change both of the above files?
- How do we build and test the plugin? (We couldn't find any contribution guide)

**Comment by naesheim** [comment]
I'm positive about both the alternatives. I can fix it myself or I can point you in the direction of using properties and then publishing a new version of the plugin. It's up to you guys.

**Comment by naesheim** [comment]
How do you currently fetch the Plugin?
And which version of gradle are you using?

**Comment by nikhilpathania** [comment]
we simply download the github project and delete everything except: gradle/wrapper, build.gradle, build.properties, gradlew.bat.
gradle version: 4.4.1

**Comment by martinmosegaard** [comment]
We are using the plugin via our artifact repository, so our `build.gradle` contains this:

```
buildscript {
  repositories {
    maven {
      url "https://our-artifact-repository/Gradle-Plugin/"
    }
  }
  dependencies {
    classpath "gradle.plugin.net.praqma:VersionedBinaryArtifacts:2.0.0"
  }
}

apply plugin: "net.praqma.vba"
```

**Comment by martinmosegaard** [comment]
Thanks @naesheim . It would be great if you can fix it. Let us know if you need input along the way.

**Comment by naesheim** [comment]
I will start on this tomorrow and notify you @martinmosegaard if anything appears.

**Comment by naesheim** [comment]
The hardcoded resolveDep path was to ensure that the dependencies of the depency was added in the buildInfo.properties file in the dep/ folder. Are you using this feature? @nikhilpathania

**Comment by nikhilpathania** [comment]
no we are not using that feature

**Comment by naesheim** [comment]
Would you be interested in using the plugin if I published it to plugins.gradle.com?
The only needed code you need would be:

plugins {
 id “net.praqma.vba” version “2.0.1"
}

Also, is it ok to pass a property in the build.properties? for instance 

resolvedDepDir=your/ideal/path

**Comment by naesheim** [comment]
@martinmosegaard @nikhilpathania

**Comment by jonasvinther** [comment]
Yes it would make sense to add it as a property to the build.properties file. That would be really great.

I also think that you should publish the update to plugins,gradle.com. It's a nice little feature to add to the project.

**Comment by naesheim** [comment]
@martinmosegaard @nikhilpathania @jonasvinther 
Feel free to test the functionality now: 

plugins {
id “net.praqma.vba” version “2.0.1"
}

Set your wanted path in build.properties with

resolvedDepDir=your/ideal/path

**Comment by nikhilpathania** [comment]
worked like a charm...this issue can be closed.
