### ISSUE TITLE
Special character in the dependency name cause problem

### ISSUE THREAD

**Issue by nikhilpathania** [Praqma/VersionedBinaryArtifacts#16]
This issue experienced is while downloading dependencies. 
Our **_build.properties_** file is as shown below:
```group=
version=
publishRepo=
artifact=
buildWorkingDir=
buildCmd=
dependencies=net.xyz:rti-connext-dds:0.0.1
resolvedDepDir=3rdParty
```
If the dependency name contains **_"-"_**, then the script downloads the dependencies in the following folder structure:
```
/3rdParty/rti/rti-connext-dds/
/3rdParty/rti/dep/
```

expected:

```
/3rdParty/rti-connext-dds/rti-connext-dds/
/3rdParty/rti-connext-dds/dep/
```

**Comment by naesheim** [comment]
Did this occur due to the latest change?

**Comment by nikhilpathania** [comment]
no...it was present way before

**Comment by jonasvinther** [comment]
No this was also a problem before the latest update.

**Comment by naesheim** [comment]
Yes. It is so in order to split the dependency name from the version. (combined with a dash -)

I'll see if it is an easy fix or its easier to rename dependencies(replace - with _).

**Comment by naesheim** [comment]
I can fix it.

**Comment by naesheim** [comment]
@nikhilpathania Do you have dash (-) in the version name?
ex 1.0.0-rc3 ?

**Comment by nikhilpathania** [comment]
we dont use (-)

**Comment by MadsBaggesen** [comment]
But I could see it in other cases - like 1.2.3-SNAPSHOT? I think that is a quite common pattern...

**Comment by naesheim** [comment]
Yes. I agree. Its just a way to avoid having the full dependecy name in the tree.
Thats why I do a String name = it.getName().split('-')[0]

**Comment by naesheim** [comment]
plugins {
 id “net.praqma.vba” version “2.0.2"
}

try it out. I havent tested it as much as I would want, so let me know if something is off.

**Comment by nikhilpathania** [comment]
tested and worked fine...this ticket can be closed...thank you so much @naesheim
