### ISSUE TITLE
Don't overwrite buildinfo file when there are multiple dependencies

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/VersionedBinaryArtifacts#2]
Right now, when multiple dependencies are specified the second artifacts buildinfo file is overwritten.  We have options:
- Make each buildinfo file a unique name
- Put each dependency in a separate folder
- Create a flag to specify new behavior

I go for the first option so that it does not break existing functionality, and we don't have divergent logic.

So the buildinfo files should be called `<artifactName>.buildInfo`

**Comment by naesheim** [comment]
buidInfo for each dependency is put in a seperate tree structure <depName>/dev/buildInfo
